title: Henry Stanley
description: "Henry Stanley — Director of Technology at Effektiv Spenden, writing from Berlin about software, philosophy and whatever else."
email: &email henry@henrystanley.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.henrystanley.com"

markdown: kramdown

timezone: UTC

plugins:
- jekyll-redirect-from

github:
  repo: henryaj/henryaj.github.io
  branch: master

# About/contact
author:
  name:              Henry Stanley
  url:               https://www.henrystanley.com
  email:             *email

permalink: /:title/
