title: Henry Stanley
# tagline:
email: &email henry@henrystanley.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://henrystanley.com"

markdown: kramdown

timezone: UTC

paginate: 5

gems:
- jekyll-redirect-from

github:
  repo: henryaj/henryaj.github.io
  branch: master

# About/contact
author:
  name:              Henry Stanley
  url:               http://henrystanley.com
  email:             *email

permalink: /:title/
